---
title: "Stage Five WGCNA Analysis"
date: "`r format(Sys.time(), '%A, %d %B, %Y')`"
output: 
  html_document:
  self_contained: true
params:
  stage: 5
  softpower: 7
---

```{r setup, echo = F}
knitr::opts_chunk$set(echo = F, warning = F, message = F, cache = F, include = T)
```

```{r libraries, cache = F}
#Part 1: Data input and cleaning

library(WGCNA)

# Tue May 12 11:15:45 2020 ------------------------------
if (!require("pacman")) install.packages("pacman")
pacman::p_load(ABAData, httr, readxl, tidyverse, patchwork, ggplotify, janitor, ggrepel, ggtext, glue)
theme_set(theme_minimal())
```

```{r data_input, cache = T}
url <- "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5918692/bin/NIHMS958804-supplement-Supplementary_Table.xlsx"
GET(url, write_disk(temp_file <- tempfile(fileext = ".xlsx"))) # downloads the .xlsx file
df <- read_excel(temp_file, sheet = 5, skip = 6) # reads into a dataframe. First six rows of the excel file are just header
unlink(temp_file)     # deletes the temporary file


##################################################################
# makes sz_genes, a dataframe with a single column of the CLOZUK genes
#######################################################################

all_sz_genes <- df$`Gene(s) tagged` %>% 
  str_split(",") %>% 
  unlist() %>% 
  str_trim() %>% 
  as.data.frame() %>% 
  distinct()
names(all_sz_genes) <- "genes"

data(dataset_5_stages)
```

```{r choose_stage}
stage <- 5

sz_stage_function <-  function(stage = 5){
  dataset_5_stages %>%
    filter(hgnc_symbol %in% all_sz_genes$genes) %>% 
    filter(age_category == stage) %>% 
    dplyr::select(-c(entrezgene, ensembl_gene_id, age_category)) %>% 
    pivot_wider(names_from = structure, values_from = signal) %>% 
    column_to_rownames(var = "hgnc_symbol")%>%
    t() %>% 
    scale() %>% 
    t()
}

sz_stage_5 <- sz_stage_function(stage = stage)
k5 <- sz_stage_5 %>% t()
```

```{r soft_threshold}
powers5 = c(c(1:10), seq(from = 12, to=20, by=2))

# Call the network topology analysis function
sft5 = pickSoftThreshold(k5, powerVector = powers5, verbose = 5)

# # Plot the results:
# sizeGrWindow(9, 5)
# par(mfrow = c(1,2));
cex1 = 0.9;
# 
# Scale-free topology fit index as a function of the soft-thresholding power
p1 = sft5$fitIndices %>% 
  clean_names() %>% 
  ggplot(aes(power, y = -sign(slope)*sft_r_sq, label = powers5)) +
  labs(x = "Soft Threshold (power)",
       y = "Scale Free Topology Model Fit, signed R<sup>2</sup>",
       title = "Scale independence") +
  geom_point() +
  geom_text_repel() +
  theme(axis.title.y = element_textbox_simple(
      orientation = "left-rotated",
      width = NULL)) +
  geom_hline(yintercept = 0.55, col = "red" )

# Mean connectivity as a function of the soft-thresholding power
p2 = sft5$fitIndices %>% 
  clean_names() %>% 
  ggplot(aes(power, y = mean_k, label = powers5)) +
  labs(x = "Soft Threshold (power)",
       y = "Mean Connectivity",
       title = "Mean Connectivity") +
  geom_point() +
  geom_text_repel()

p1 + p2

```

```{r adjacencies}
#Calculating adjacincies with soft threshold of params$softpower
softPower5 = params$softpower
adjacency5 = adjacency(k5, power = softPower5);

# Turn adjacency into topological overlap 
TOM5 = TOMsimilarity(adjacency5); 
dissTOM5 = 1-TOM5

# Call the hierarchical clustering function 
geneTree5 = hclust(as.dist(dissTOM5), method = "average")
# Plot the resulting clustering tree (dendrogram) 
plot(geneTree5, xlab="", sub="", main = glue("Gene clustering on TOM-based dissimilarity\nfor schizophrenia genes during stage {stage}"), labels = FALSE, hang = 0.04)
```

```{r dendro_colours}
# We like large modules, so we set the minimum module size relatively high: 
minModuleSize = 10; 
# Module identification using dynamic tree cut: 
dynamicMods5 = cutreeDynamic(dendro = geneTree5, distM = dissTOM5, deepSplit = 2, pamRespectsDendro = FALSE, minClusterSize = minModuleSize); 
table(dynamicMods5)

# Convert numeric lables into colors 
dynamicColors5 = labels2colors(dynamicMods5) 
table(dynamicColors5) 
# Plot the dendrogram and colors underneath 
plotDendroAndColors(geneTree5, 
                    dynamicColors5, 
                    "Dynamic Tree Cut", 
                    dendroLabels = FALSE, 
                    hang = 0.03, 
                    addGuide = TRUE, 
                    guideHang = 0.05, 
                    main = glue("Age category {stage} colour dendrogram"))


# Tue May 12 11:35:46 2020 ------------------------------
MEList5 = moduleEigengenes(sz_stage_5 %>% t(), colors = dynamicMods5)
 # Tue May 12 11:35:52 2020 ------------------------------

MEs5 = MEList5$eigengenes 
# Calculate dissimilarity of module eigengenes 
MEDiss5 = 1-cor(MEs5); 
# Cluster module eigengenes 
METree5 = hclust(as.dist(MEDiss5), method = "average"); 
# Plot the result 
plot(METree5, main = glue("Clustering of module eigengenes for stage  {stage}"), xlab = "", sub = "")
```

```{r more_dendro_colours, fig.height=12, fig.width=16}

MEDissThres5 = 1
# Plot the cut line into the dendrogram
# abline(h=MEDissThres5, col = "red")
# Call an automatic merging function
merge5 = mergeCloseModules(k5, dynamicColors5, cutHeight = MEDissThres5, verbose = 3)
# The merged module colors
mergedColors5 = merge5$colors;
# Eigengenes of the new merged modules:
mergedMEs5 = merge5$newMEs

plot(geneTree5, 
     main = "Sample clustering to detect outliers", 
     sub="", 
     xlab="", 
     cex.lab = 0.5, 
     cex.axis = 1.5, 
     cex.main = 2, 
     cex = 0.6, 
     labels = colnames(k5))

plotDendroAndColors(geneTree5, 
                    cbind(dynamicColors5, mergedColors5),
                    c("Dynamic Tree Cut", "Merged dynamic"),
                    dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05)


# Tue May 12 11:35:46 2020 ------------------------------
MEList5 = moduleEigengenes(sz_stage_5 %>% t(), colors = dynamicMods5)
# Tue May 12 11:35:52 2020 ------------------------------

MEDissThres5 = 1
# Plot the cut line into the dendrogram
abline(h=MEDissThres5, col = "red")
# Call an automatic merging function
merge5 = mergeCloseModules(k5, dynamicColors5, cutHeight = MEDissThres5, verbose = 3)
# The merged module colors
mergedColors5 = merge5$colors;
geneInfoALL5 <- data.frame(geneIDs = colnames(k5), 
                           moduleColor=mergedColors5)
geneInfoALL5 %>% 
  arrange(moduleColor) %>% 
  knitr::kable()
# Eigengenes of the new merged modules:
mergedMEs5 = merge5$newMEs
#pdf(file = "Plots/geneDendro-3.pdf", wi = 9, he = 6)
plotDendroAndColors(geneTree5, cbind(dynamicColors5, mergedColors5),
                    c("Dynamic Tree Cut", "Merged dynamic"),
                    dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05)
```

```{r METree}
# Rename to moduleColors
moduleColors5 = mergedColors5
# Construct numerical labels corresponding to the colors
colorOrder5 = c("grey", standardColors(50));
moduleLabels5 = match(moduleColors5, colorOrder5)-1;
MEs5 = mergedMEs5;

MEs50 = moduleEigengenes(k5, moduleColors5)$eigengenes
MEs55 = orderMEs(MEs50)
#View(MEs50)
MEs5 = MEList5$eigengenes 
# Calculate dissimilarity of module eigengenes 
MEDiss5 = 1-cor(MEs5); 
# Cluster module eigengenes 
METree5 = hclust(as.dist(MEDiss5), method = "average"); 
# Plot the result 
plot(METree5, main = glue("Clustering of module eigengenes for age category  {stage}"), xlab = "", sub = "")
```

```{r dissTOM, eval = T}
# Calculate topological overlap anew: this could be done more efficiently by saving the TOM
# calculated during module detection, but let us do it again here.
dissTOM5 = 1-TOMsimilarityFromExpr(k5, power = params$softpower);
# Transform dissTOM with a power to make moderately strong connections more visible in the heatmap
plotTOM5 = dissTOM5^params$softpower;
# Set diagonal to NA for a nicer plot
diag(plotTOM5) = NA;
# Call the plot function
TOMplot(plotTOM5, geneTree5, moduleColors5, main = glue("Network heatmap plot, all sz genes, stage  {stage}"))

# MEs5 = moduleEigengenes(k5, moduleColors5)$eigengenes
# par(cex = 0.9)
# if(ncol(MEs5) > 2)  plotEigengeneNetworks(MEs5, "", marDendro = c(0,4,1,2), marHeatmap = c(3,4,1,2), cex.lab = 0.8, xLabelsAngle = 90)
```

```{r hubgenes_etc, eval=T}

# Plot the dendrogram
par(cex = 1.0)
if(ncol(MEs5) > 2) plotEigengeneNetworks(MEs5, glue("Eigengene dendrogram for stage  {stage}"), marDendro = c(0,4,2,0), plotHeatmaps = FALSE)
# Plot the heatmap matrix (note: this plot will overwrite the dendrogram plot)
par(cex = 1.0)
if(ncol(MEs5) > 2) plotEigengeneNetworks(MEs5, glue("Eigengene adjacency heatmap for stage  {stage}"), marHeatmap = c(3,4,2,2), plotDendrograms = FALSE, xLabelsAngle = 90)

moduleEigengenes(k5,
                 moduleColors5,
                 impute = TRUE,
                 nPC = 1,
                 align = "along average",
                 excludeGrey = FALSE,
                 grey = if (is.numeric(moduleColors1)) 0 else "grey",
                 subHubs =TRUE,
                 softPower = params$softpower,
                 scale = TRUE,
                 verbose = 0, indent = 0)

chooseTopHubInEachModule(
  k5,
  moduleColors5,
  omitColors = "grey",
  power = params$softpower,
  type = "unsigned")

geneModuleMembership5 = as.data.frame(cor(k5, MEs55, use = "p"))


# Wed Aug 26 13:49:54 2020 ------------------------------
# Wed Aug 26 13:50:01 2020 ------------------------------


# # Recalculate module eigengenes
# MEs5 = moduleEigengenes(k5, moduleColors5)$eigengenes
# 
# if(ncol(MEs5) > 2)  plotEigengeneNetworks(MEs5, "", marDendro = c(0,4,1,2), marHeatmap = c(3,4,1,2), cex.lab = 0.8, xLabelsAngle = 90)
# 

```
